package blir.engine.swing;

import java.util.Collection;

/**
 *
 * @author Blir
 * @param <E> the value being selected
 */
public abstract class SelectorGUI<E> extends javax.swing.JFrame {

    private final javax.swing.DefaultListModel<E> model = new javax.swing.DefaultListModel<>();
    private final int DEFAULT_CLOSE_OPERATION;

    public SelectorGUI(Collection<E> values, int defaultCloseOperation) {
        this.DEFAULT_CLOSE_OPERATION = defaultCloseOperation;
        initComponents();
        for (E value : values) {
            model.addElement(value);
        }
        setLocationRelativeTo(null);
    }

    public SelectorGUI(E[] values, int defaultCloseOperation) {
        this.DEFAULT_CLOSE_OPERATION = defaultCloseOperation;
        initComponents();
        for (E value : values) {
            model.addElement(value);
        }
        setLocationRelativeTo(null);
    }

    public abstract void onSelectionMade(E selection);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<E>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(this.DEFAULT_CLOSE_OPERATION);
        setTitle("Selector");

        jList1.setModel(this.model);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelect(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelect
        if (jList1.getSelectedValue() != null) {
            onSelectionMade(jList1.getSelectedValue());
            dispose();
        }
    }//GEN-LAST:event_onSelect
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<E> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
